spring.application.name=market-exchange
spring.datasource.url=jdbc:postgresql://localhost:5432/market_exchange
spring.datasource.username=market_user
spring.datasource.password=market_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
